# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PolicyRole', to='users.Policy')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RolePolicy', to='users.Role')),
            ],
        ),
    ]
